[workspace]
members = ["shadowquic-lib", "shadowquic-macros"]
default-members = ["shadowquic-lib"]

[workspace.package]
name = "shadowquic"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
