[workspace]
members = ["shadowquic-lib", "shadowquic-macros","perf"]
default-members = ["shadowquic-lib"]
resolver = "3"

[workspace.package]
name = "shadowquic"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
