[workspace]
members = ["shadowquic-lib", "shadowquic-macros","perf"]
default-members = ["shadowquic-lib"]
resolver = "3"


[workspace.package]
name = "shadowquic"
version = "0.1.0"
edition = "2024"
authors = ["spongebob888"]
homepage = "https://github.com/spongebob888/shadowquic"
repository = "https://github.com/spongebob888/shadowquic.git"


[workspace.dependencies]
