[package]
name = "shadowquic-macros"
version = "0.1.0"
repository = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["extra-traits"] }


